- name: "run test"
  hosts: all
  become: yes

  tasks:
  - name: Change dir
    shell: >
        cd /root/Downloads/Postman/allure-results
    become: yes

  - name: Allure test
    shell: >
        /allure-1.0.0-e98dce0b638313a702f42b7e6cbac694323/bin/allure serve -p 40000
    become: yes

