- name: "run test"
  hosts: all
  become: yes

  tasks:
  - name: Run test
    shell: |
        cd /root/Desktop/playwright/tests
        npx playwright test openstack-project.spec.js openstack-creation-az.spec.js --reporter=line,allure-playwright
        /allure/bin/allure serve -p 32700
    become: yes
