- name: "run test"
  hosts: compute
  become: yes

  tasks:
  - name: Run test
    shell: |
        echo "Connection succesfull"
    become: yes

  - name: Create json result
    ansible.builtin.blockinfile:
      path: /tmp/ssh-result.json
      block: |
        {"uuid":"ssh-test","historyId":"ssh-test","status":"passed","statusDetails":{"message":"Succesfull connected to compute node"},"stage":"pending","steps":[{"status":"passed","statusDetails":{},"stage":"pending","steps":[],"attachments":[],"parameters":[],"name":"INFO"}],"attachments":[],"parameters":[],"labels":[{"name":"parentSuite","value":"Ansible-Tests/SSH"},{"name":"suite","value":"Connection test"}],"links":[],"name":"ssh-test","fullName":"ssh-test"}
    become: yes
