- name: "upgrade director"
  hosts: undercloud

  tasks:
  - name: Lock the undercloud to a 8.4 release
    shell: |
        sudo subscription-manager release --set=8.4
    become_user: stack

  - name: Subscriptions
    shell: |
        sudo subscription-manager repos --disable=*
        sudo subscription-manager repos --enable=rhel-8-for-x86_64-baseos-eus-rpms --enable=rhel-8-for-x86_64-appstream-eus-rpms --enable=rhel-8-for-x86_64-highavailability-eus-rpms --enable=ansible-2.9-for-rhel-8-x86_64-rpms --enable=openstack-16.2-for-rhel-8-x86_64-rpms --enable=fast-datapath-for-rhel-8-x86_64-rpms
    become_user: stack

  - name: Set the container-tools repository module to version 3.0
    shell: |
        sudo dnf module reset -y  container-tools
        sudo dnf module enable -y container-tools:3.0
    become_user: stack

  - name: Synchronize the operating system
    shell: |
        sudo dnf distro-sync -y
        sudo reboot
    become_user: stack
